### PR TITLE
ViewFactory: add variant of makeMessageListContainerModifier with channel

### PR DESCRIPTION
**Pull request by AndrewSB**
i've just added a new view factory function with a channel param. shouldn't be a breaking change

### ☑️ Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [ ] Changelog is updated with client-facing changes
- [ ] New code is covered by unit tests
- [ ] Affected documentation updated (docusaurus, tutorial, CMS (task created)

### CODE REVIEW

**Comment by martinmitrevski** [comment]
Hey @AndrewSB, thanks for raising the PR. It's not a breaking change, but it will be confusing for our customers to have 2 versions of the same method and long term it won't be scalable for us to maintain that. Therefore, we will close this PR, but will keep it in mind for a major version release.

**Comment by AndrewSB** [comment]
got it, i'm going to have to maintain a fork until this is included upstream, so i'd really appreciate this making it into your version

**Comment by martinmitrevski** [comment]
one idea to overcome this: keep the currently selected channel as a var in your factory and then pass it in the modifier method we already have.

**Comment by AndrewSB** [comment]
could do, but i'm worried about some sort of edge case where we don't clear that channel/we deeplink into another channel and don't update the var in time

**Comment by AndrewSB** [comment]
@martinmitrevski what if we added an `unsafe_` prefix to this function? 

it would technically enter your API compatibility, but with the unsafe prefix, i think it would be totally fair for you to break the API once there's a major release?

**Pull request closed without merging**
